### ISSUE TITLE
Naming Convention in Linux

### ISSUE THREAD

**Issue by Acrylangel** [arkadiusjonczek/digistore24#1]
Hello there,

i just found a bug in your implementation. Your naming convention does not comply to psr4 and will result in class not found errors on linux based systems. You have to either rename the files to reflect the class definition or change the class definitions.

greetings :)

**Comment by arkadiusjonczek** [comment]
Hi @Acrylangel, sorry for the late feedback. I didn't get any notification.

I think you mean the lowercase "s" of store in DigistoreApi.php, right?

Can you open a pull request? :)

**Comment by arkadiusjonczek** [comment]
Was fixed with:
https://github.com/arkadiusjonczek/digistore24/commit/282bf44749a3d560e07b89be2f415e51d85c7726
https://github.com/arkadiusjonczek/digistore24/commit/f94d551d24f8495291180fb14a7831d1a71154ce

**Comment by contaoacademy** [comment]
Can you please publish a new release so that the changes are automatically integrated when installing via composer. Otherwise I would have to use dev-master insted of the release 1.1.

**Comment by auipga** [comment]
@arkadiusjonczek ping
Please add a `1.1.1` tag / release.

**Comment by arkadiusjonczek** [comment]
@contaoacademy @auipga done
